# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\workspace\LolGameAssistant\emptybox\ItemChanger.ui'
#
# Created: Thu Jul 19 06:44:02 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(367, 313)
        Dialog.setMinimumSize(QtCore.QSize(367, 313))
        Dialog.setMaximumSize(QtCore.QSize(367, 313))
        Dialog.setSizeGripEnabled(False)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pathEdit = QtGui.QLineEdit(Dialog)
        self.pathEdit.setObjectName(_fromUtf8("pathEdit"))
        self.horizontalLayout_2.addWidget(self.pathEdit)
        self.browseButton = QtGui.QPushButton(Dialog)
        self.browseButton.setAutoDefault(False)
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.horizontalLayout_2.addWidget(self.browseButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.champBox = QtGui.QComboBox(Dialog)
        self.champBox.setObjectName(_fromUtf8("champBox"))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.champBox.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.champBox)
        self.fiveBox = QtGui.QComboBox(Dialog)
        self.fiveBox.setEnabled(False)
        self.fiveBox.setObjectName(_fromUtf8("fiveBox"))
        self.verticalLayout.addWidget(self.fiveBox)
        self.oneBox = QtGui.QComboBox(Dialog)
        self.oneBox.setEnabled(False)
        self.oneBox.setObjectName(_fromUtf8("oneBox"))
        self.verticalLayout.addWidget(self.oneBox)
        self.twoBox = QtGui.QComboBox(Dialog)
        self.twoBox.setEnabled(False)
        self.twoBox.setObjectName(_fromUtf8("twoBox"))
        self.verticalLayout.addWidget(self.twoBox)
        self.sixBox = QtGui.QComboBox(Dialog)
        self.sixBox.setEnabled(False)
        self.sixBox.setObjectName(_fromUtf8("sixBox"))
        self.verticalLayout.addWidget(self.sixBox)
        self.threeBox = QtGui.QComboBox(Dialog)
        self.threeBox.setEnabled(False)
        self.threeBox.setObjectName(_fromUtf8("threeBox"))
        self.verticalLayout.addWidget(self.threeBox)
        self.fourBox = QtGui.QComboBox(Dialog)
        self.fourBox.setEnabled(False)
        self.fourBox.setObjectName(_fromUtf8("fourBox"))
        self.verticalLayout.addWidget(self.fourBox)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.saveButton = QtGui.QPushButton(Dialog)
        self.saveButton.setDefault(True)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.gridLayout.addWidget(self.saveButton, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "League of Legends Item Changer", None, QtGui.QApplication.UnicodeUTF8))
        self.pathEdit.setText(QtGui.QApplication.translate("Dialog", "Path to League Client", None, QtGui.QApplication.UnicodeUTF8))
        self.browseButton.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(0, QtGui.QApplication.translate("Dialog", "Champion", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(1, QtGui.QApplication.translate("Dialog", "Ahri", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(2, QtGui.QApplication.translate("Dialog", "Akali", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(3, QtGui.QApplication.translate("Dialog", "Alistar", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(4, QtGui.QApplication.translate("Dialog", "Amumu", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(5, QtGui.QApplication.translate("Dialog", "Anivia", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(6, QtGui.QApplication.translate("Dialog", "Annie", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(7, QtGui.QApplication.translate("Dialog", "Ashe", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(8, QtGui.QApplication.translate("Dialog", "Blitzcrank", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(9, QtGui.QApplication.translate("Dialog", "Brand", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(10, QtGui.QApplication.translate("Dialog", "Caitlyn", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(11, QtGui.QApplication.translate("Dialog", "Cassiopeia", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(12, QtGui.QApplication.translate("Dialog", "Cho\'Gath", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(13, QtGui.QApplication.translate("Dialog", "Corki", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(14, QtGui.QApplication.translate("Dialog", "Darius", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(15, QtGui.QApplication.translate("Dialog", "Dr. Mundo", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(16, QtGui.QApplication.translate("Dialog", "Draven", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(17, QtGui.QApplication.translate("Dialog", "Evelynn", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(18, QtGui.QApplication.translate("Dialog", "Ezreal", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(19, QtGui.QApplication.translate("Dialog", "Fiddlesticks", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(20, QtGui.QApplication.translate("Dialog", "Fiora", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(21, QtGui.QApplication.translate("Dialog", "Fizz", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(22, QtGui.QApplication.translate("Dialog", "Galio", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(23, QtGui.QApplication.translate("Dialog", "Gangplank", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(24, QtGui.QApplication.translate("Dialog", "Gragas", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(25, QtGui.QApplication.translate("Dialog", "Graves", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(26, QtGui.QApplication.translate("Dialog", "Hecarim", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(27, QtGui.QApplication.translate("Dialog", "Heimerdinger", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(28, QtGui.QApplication.translate("Dialog", "Irelia", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(29, QtGui.QApplication.translate("Dialog", "Janna", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(30, QtGui.QApplication.translate("Dialog", "Jarvan IV", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(31, QtGui.QApplication.translate("Dialog", "Jax", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(32, QtGui.QApplication.translate("Dialog", "Karma", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(33, QtGui.QApplication.translate("Dialog", "Karthus", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(34, QtGui.QApplication.translate("Dialog", "Kassadin", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(35, QtGui.QApplication.translate("Dialog", "Katarina", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(36, QtGui.QApplication.translate("Dialog", "Kayle", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(37, QtGui.QApplication.translate("Dialog", "Kennen", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(38, QtGui.QApplication.translate("Dialog", "Kog\'Maw", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(39, QtGui.QApplication.translate("Dialog", "LeBlanc", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(40, QtGui.QApplication.translate("Dialog", "Lee Sin", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(41, QtGui.QApplication.translate("Dialog", "Leona", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(42, QtGui.QApplication.translate("Dialog", "Lulu", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(43, QtGui.QApplication.translate("Dialog", "Lux", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(44, QtGui.QApplication.translate("Dialog", "Malphite", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(45, QtGui.QApplication.translate("Dialog", "Malzahar", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(46, QtGui.QApplication.translate("Dialog", "Maokai", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(47, QtGui.QApplication.translate("Dialog", "Master Yi", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(48, QtGui.QApplication.translate("Dialog", "Miss Fortune", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(49, QtGui.QApplication.translate("Dialog", "Mordekaiser", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(50, QtGui.QApplication.translate("Dialog", "Morgana", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(51, QtGui.QApplication.translate("Dialog", "Nasus", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(52, QtGui.QApplication.translate("Dialog", "Nautilus", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(53, QtGui.QApplication.translate("Dialog", "Nidalee", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(54, QtGui.QApplication.translate("Dialog", "Nocturne", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(55, QtGui.QApplication.translate("Dialog", "Nunu", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(56, QtGui.QApplication.translate("Dialog", "Olaf", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(57, QtGui.QApplication.translate("Dialog", "Orianna", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(58, QtGui.QApplication.translate("Dialog", "Pantheon", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(59, QtGui.QApplication.translate("Dialog", "Poppy", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(60, QtGui.QApplication.translate("Dialog", "Rammus", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(61, QtGui.QApplication.translate("Dialog", "Renekton", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(62, QtGui.QApplication.translate("Dialog", "Riven", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(63, QtGui.QApplication.translate("Dialog", "Rumble", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(64, QtGui.QApplication.translate("Dialog", "Ryze", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(65, QtGui.QApplication.translate("Dialog", "Sejuani", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(66, QtGui.QApplication.translate("Dialog", "Shaco", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(67, QtGui.QApplication.translate("Dialog", "Shen", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(68, QtGui.QApplication.translate("Dialog", "Shyvana", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(69, QtGui.QApplication.translate("Dialog", "Singed", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(70, QtGui.QApplication.translate("Dialog", "Sion", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(71, QtGui.QApplication.translate("Dialog", "Sivir", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(72, QtGui.QApplication.translate("Dialog", "Skarner", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(73, QtGui.QApplication.translate("Dialog", "Sona", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(74, QtGui.QApplication.translate("Dialog", "Soraka", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(75, QtGui.QApplication.translate("Dialog", "Swain", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(76, QtGui.QApplication.translate("Dialog", "Talong", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(77, QtGui.QApplication.translate("Dialog", "Taric", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(78, QtGui.QApplication.translate("Dialog", "Teemo", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(79, QtGui.QApplication.translate("Dialog", "Tristana", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(80, QtGui.QApplication.translate("Dialog", "Trundle", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(81, QtGui.QApplication.translate("Dialog", "Tryndamere", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(82, QtGui.QApplication.translate("Dialog", "Twisted Fate", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(83, QtGui.QApplication.translate("Dialog", "Twitch", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(84, QtGui.QApplication.translate("Dialog", "Udyr", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(85, QtGui.QApplication.translate("Dialog", "Urgot", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(86, QtGui.QApplication.translate("Dialog", "Varus", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(87, QtGui.QApplication.translate("Dialog", "Vayne", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(88, QtGui.QApplication.translate("Dialog", "Veigar", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(89, QtGui.QApplication.translate("Dialog", "Viktor", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(90, QtGui.QApplication.translate("Dialog", "New Item", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(91, QtGui.QApplication.translate("Dialog", "Vladimir", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(92, QtGui.QApplication.translate("Dialog", "Volibear", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(93, QtGui.QApplication.translate("Dialog", "Warwick", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(94, QtGui.QApplication.translate("Dialog", "Wukong", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(95, QtGui.QApplication.translate("Dialog", "Xerath", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(96, QtGui.QApplication.translate("Dialog", "Xin Zhao", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(97, QtGui.QApplication.translate("Dialog", "Yorick", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(98, QtGui.QApplication.translate("Dialog", "Ziggs", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(99, QtGui.QApplication.translate("Dialog", "Zilean", None, QtGui.QApplication.UnicodeUTF8))
        self.champBox.setItemText(100, QtGui.QApplication.translate("Dialog", "Zyra", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))

